ARG UBUNTU_VERSION=24.04
FROM ubuntu:${UBUNTU_VERSION} AS base

ARG UID
ARG GID

ENV DEBIAN_FRONTEND=noninteractive

# A) Install essential software
 RUN mkdir -p /tmp/pkg
COPY scripts/pkg-install/*.sh /tmp/pkg
 RUN chmod a+x /tmp/pkg/*.sh
 RUN /tmp/pkg/run_essential.sh

# B) Setup lab user
RUN getent group  "$GID" > /dev/null || addgroup --gid $GID lab
RUN getent group  "$GID" > /dev/null && export GNAME=$(getent group  "$GID" | cut -d: -f1) && sudo groupmod -n lab "$GNAME"
RUN getent passwd "$UID" > /dev/null || adduser  --uid $UID --gid $GID --disabled-password --gecos "" lab
RUN getent passwd "$UID" > /dev/null && export UNAME=$(getent passwd "$UID" | cut -d: -f1) && sudo usermod  -l lab -m -d /home/lab "$UNAME"

RUN echo 'lab ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
RUN echo 'lab:lab' | sudo chpasswd

RUN mkdir -p  /home/lab/bin  /home/lab/test  /home/lab/replication  /home/lab/spark  /home/lab/benchmark
ADD lab-home/bin          /home/lab/bin
ADD lab-home/test         /home/lab/test
ADD lab-home/spark        /home/lab/spark
ADD lab-home/benchmark    /home/lab/benchmark
ADD lab-home/replication  /home/lab/replication
RUN chown -R lab:lab      /home/lab

# C) OpenSSH: keygen
USER lab
 RUN mkdir -p  /home/lab/.ssh
 RUN chmod 700 /home/lab/.ssh
 RUN ssh-keygen -q -t rsa -N "" -f /home/lab/.ssh/id_rsa
 RUN ssh-keygen -q -t dsa -N "" -f /home/lab/.ssh/id_dsa
 RUN cat /home/lab/.ssh/id_dsa.pub >> /home/lab/.ssh/authorized_keys
 RUN cat /home/lab/.ssh/id_rsa.pub >> /home/lab/.ssh/authorized_keys

# D) Install MPICH and XPN (from source)
USER root
 RUN mkdir -p /tmp/src
COPY scripts/src-install/*.sh /tmp/src
 RUN chmod a+x /tmp/src/*.sh
USER lab
 RUN /tmp/src/run_all.sh /home/lab/src/

# User initial home
USER lab
RUN sudo chmod a+x /home/lab/*/*.sh
RUN sudo chown -R lab:lab /home/lab
WORKDIR "/home/lab"

# Container start-up
USER root
RUN mkdir -p /work
RUN mkdir -p /srv
COPY docker/dockerstart.sh /srv/

EXPOSE 22
CMD ["/srv/dockerstart.sh"]
